{% set version = "0.8-104" %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-logging
  version: {{ version|replace("-", "_") }}

source:
  fn: logging_{{ version }}.tar.gz
  url:
    - https://cran.r-project.org/src/contrib/logging_{{ version }}.tar.gz
    - https://cran.r-project.org/src/contrib/Archive/logging/logging_{{ version }}.tar.gz
  sha256: 3d46b00a436700635878edec954c7d962bea93193f61af673895220b3d213dbf

build:
  noarch: generic
  number: 1000
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  host:
    - r-base

  run:
    - r-base

test:
  commands:
    - $R -e "library('logging')"  # [not win]
    - "\"%R%\" -e \"library('logging')\""  # [win]

about:
  home: https://CRAN.R-project.org/package=logging
  license: GPL (>= 2)
  summary: logging is a pure R package that implements the ubiquitous log4j package.
  license_family: GPL3

extra:
  recipe-maintainers:
    - dpryan79
    - johanneskoester
    - bgruening
