appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
provider: {win: azure}
travis:
  secure: {BINSTAR_TOKEN: dzTEA/q5LfsNZdygnTnOvom0hvpzYpXL4I9ayEuAuUu5nuV33iMDz2InnfAKQYIcOe7Xq0TI0WT2nV6u2HuUNFhI/HT0sKvQunbX0tVgU31hQS6Tt5qrGIecRFUKtCcPesst+2x0KPkREENJhVnvpaumISFFfb44t8AT6zPpZLCW2j2qpbxGoCgWSTojqGstRmRNWBppWcYsCE2ctJ8SSk+D08Rloc1xyJ2I0uDA0ILuCSFswScXMmsf/ugBbD8h3kMmiM/vprVlwifoM5j0FrhfQ8/q9Oi6aiaZfacN2h3mO6/3kgXQ50QPCg85K7M3dG4m1Hz9KvLwfxKuo4NSrPDQR/8ucS/TLGaCoIZAV+Ega11tFc11UH+tAAvd4jrpZ7Ip4G8nmRrn2f2cdNDMjQ9/D3RRs5/rkbnB64FWLoPEPSYGEUu/4Ehs9boIkCQlqZOa2S4aHtHMjCsZMlZH4wJmicPRgBKs6gvRVWpip02TTSZNWf8fdX9T9GocqH5oC6KgvuipnAa2SkWctzrM7YIyOBz5qq5zxvIbcoIfEj3G9qMP+K2dRH/IMiIT6QKP6iqxmNr78OxDFYYVRrAaEG1unXn5h+ObSkLJrwTLztInWVVgdNQe6r6n9bREe6am2drAS+gvlfYvMbpLqTKseiKUnweC3NRQiBnofSy3BfA=}
bot:
  automerge: true
